ToyStoryApplication/Controllers/FranchisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToyStoryApplication.Models;

namespace ToyStoryApplication.Controllers
{
    public class FranchisesController : Controller
    {
        private ToyDBEntities db = new ToyDBEntities();

        // GET: Franchises
        public ActionResult Index()
        {
            return View(db.Franchise.ToList());
        }

        public ActionResult _Indexpartial(int? id)
        {
            Franchise franchise = db.Franchise.Single(m => m.Id == id);
            return PartialView(franchise);
        }

        [HttpPost]
        public ActionResult Like(int? id)
        {
            Franchise franchise = db.Franchise.Single(m => m.Id == id);
            if (franchise == null)
                return HttpNotFound();
            int currentLikes = franchise.Count;
            franchise.Count = currentLikes + 1;
            db.SaveChanges();
            return PartialView("_Indexpartial", franchise);
        }

        // GET: Franchises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Franchise franchise = db.Franchise.Find(id);
            if (franchise == null)
            {
                return HttpNotFound();
            }
            return View(franchise);
        }

        // GET: Franchises/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Franchises/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Franchise franchise)
        {
            TryUpdateModel(franchise);
            if (ModelState.IsValid)
            {
                string imagePath = "~/Content/Images/" + franchise.ImageFile.FileName;
                franchise.Logo = imagePath;
                franchise.ImageFile.SaveAs(Server.MapPath(imagePath));
                db.Franchise.Add(franchise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(franchise);
        }

        // GET: Franchises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Franchise franchise = db.Franchise.Find(id);
            if (franchise == null)
            {
                return HttpNotFound();
            }
            return View(franchise);
        }

        // POST: Franchises/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Franchise franchise)
        {
            // We dont want count/ empty image from the edited franchise, so using the id of the
            // edited franchise, we are retrieving the record from database and applying
            // all the changes except count/ empty image.
            Franchise franchiseInDb = db.Franchise.Single(x => x.Id == franchise.Id);
            // if the user gives a new image file, update the franchise
            // in database with the given image.
            try
            {
                franchiseInDb.ImageFile = franchise.ImageFile;
                string imagePath = "~/Content/Images/" + franchiseInDb.ImageFile.FileName;
                franchiseInDb.Logo = imagePath;
                franchiseInDb.ImageFile.SaveAs(Server.MapPath(imagePath));
            }
            catch(NullReferenceException)
            {
                // No new image file choosen by the user.
            }
            franchiseInDb.Name = franchise.Name;
            franchiseInDb.Origin = franchise.Origin;
            franchiseInDb.Type = franchise.Type;
            franchiseInDb.FirstAppearance = franchise.FirstAppearance;
            franchiseInDb.CreatedBy = franchise.CreatedBy;
            TryUpdateModel(franchiseInDb);
            if (ModelState.IsValid)
            {
                db.Entry(franchiseInDb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(franchiseInDb);
        }

        // GET: Franchises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Franchise franchise = db.Franchise.Find(id);
            if (franchise == null)
            {
                return HttpNotFound();
            }
            return View(franchise);
        }

        // POST: Franchises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Franchise franchise = db.Franchise.Find(id);
            db.Franchise.Remove(franchise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToyStoryApplication/Views/Franchises/Create.cshtml
@model ToyStoryApplication.Models.Franchise

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<h3 class="text-success">Create New Franchise</h3>
@using (Html.BeginForm("Create", "Franchises", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
{
    @Html.AntiForgeryToken()
<div align="center">
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*name="ImageFile" will bind this input to the property created in class*@
                <input type="file" name="ImageFile" required class="btn btn-primary btn-sm float-left">
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @placeholder = "Enter country of origin", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstAppearance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstAppearance, new { htmlAttributes = new { @placeholder = "Enter year of first appearance", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstAppearance, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-sm createButton" />
                @Html.ActionLink(
                    "Back",
                    "Index",
                    new { },
                    new {
                        @class = "btn btn-primary btn-sm backButton",
                    }
                )
            </div>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToyStoryApplication/Views/Franchises/Delete.cshtml
@model ToyStoryApplication.Models.Franchise

@{
    ViewBag.Title = "Delete";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h3 class="text-danger">Delete @Model.Name Franchise?</h3>
    <dl class="dl-horizontal" style="margin-top:30px">
        <div class="logo-div">
            <dd>
                <img src="@Url.Content(Model.Logo)" width="200" height="200" />
            </dd>
        </div>
        <div class="details-div">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Origin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Origin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstAppearance)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstAppearance)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Count)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Count)
            </dd>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="margin-top:10px">
                    <input type="submit" value="Delete" class="btn btn-primary btn-sm deleteButton" />
                    @Html.ActionLink(
                        "Back",
                        "Index",
                        new { },
                        new {
                            @class = "btn btn-primary btn-sm backButton",
                        }
                    )

                </div>
            </div>
        </div>
    </dl>
}

ToyStoryApplication/Views/Franchises/Details.cshtml
@model ToyStoryApplication.Models.Franchise

@{
    ViewBag.Title = "Details";
}
<h3 class="text-primary">@Model.Name Franchise Details</h3>
<br />
<dl class="container centre-container">
    <div class="row">
        <div class="col-xs-12 col-md-2 col-sm-3 logo-media">
            <img src="@Url.Content(Model.Logo)" width="200" height="200" />
        </div>

        <div class="col-xs-12 col-md-4 col-sm-9 details-div details-media dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Origin)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Origin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstAppearance)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstAppearance)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Count)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Count)
            </dd>
        </div>
        <div class="col-xs-12 col-md-4 col-sm-12 video-link">
            <iframe width="336" height="189" src=@Url.Content(Model.VideoLink) frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>

    </div>
</dl>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm editButton" })
    @Html.ActionLink("Back", "Index", new { }, new { @class = "btn btn-primary btn-sm backButton", @style="float:left" })
</p>

ToyStoryApplication/Views/Franchises/Edit.cshtml
@model ToyStoryApplication.Models.Franchise

@{
    ViewBag.Title = "Edit";
}

<h3 class="text-info">Update @Model.Name Franchise</h3>
<br />
@using (Html.BeginForm("Edit", "Franchises", FormMethod.Post, new { enctype = "multipart/form-data", id = "editForm" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal edit-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="logo-div">
            <div class="form-group">
                <div class="col-md-10 image-upload ">
                    <img src="@Url.Content(Model.Logo)" width="200" height="200" />
                    <input type="file" name="ImageFile" class="btn btn-primary btn-sm float-left">
                </div>
            </div>
        </div>
        <div class="edit-div">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstAppearance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstAppearance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstAppearance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary btn-sm saveButton" />
                    @Html.ActionLink(
                        "Back",
                        "Index",
                        new { },
                        new {
                            @class = "btn btn-primary btn-sm backButton",
                        }
                    )
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToyStoryApplication/Views/Franchises/Index.cshtml
@model IEnumerable<ToyStoryApplication.Models.Franchise>

@{
    ViewBag.Title = "Index";
}
<br />
<p>
    @Html.ActionLink("Create New Franchise", "Create",new { } ,new { @class = "btn btn-primary btn-sm createButton"})
</p>
<table class="table table-hover table-striped" id="franchiseTable">
    <thead style="background-color:#a5c05b;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Logo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstAppearance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Count)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr id="@item.Id">
            @Html.Action("_Indexpartial", new { id = item.Id })
        </tr>
    }
</table>
<script>
    $(document).ready(function () {
        $('#franchiseTable').DataTable();
    });
</script>

ToyStoryApplication/Views/Franchises/_Indexpartial.cshtml
@model ToyStoryApplication.Models.Franchise

<td>
    <img src="@Url.Content(Model.Logo)" width="70" height="70" />
</td>
<td>
    @Html.DisplayFor(modelItem => Model.Name)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.Origin)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.Type)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.FirstAppearance)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.CreatedBy)
</td>
<td data-sort="@Model.Count">
    @using (Ajax.BeginForm(
        actionName:"Like",
        controllerName: "Franchises",
        routeValues: new {id = Model.Id},
        ajaxOptions: new AjaxOptions
        {
            UpdateTargetId = Model.Id.ToString(),
            InsertionMode = InsertionMode.Replace
        }
     ))
    {
        <input type="submit" value=@Model.Count.ToString() id="likeButton" class="btn btn-primary btn-sm"/>
    }
</td>

<td>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm editButton" })
    @Html.ActionLink("Details", "Details", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm detailsButton" })
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm deleteButton" })
</td>